### ISSUE TITLE
QueueManager needs to know if ResultWorker is processing

### ISSUE THREAD

**Issue by hoeyng** [hft-swp2-ws1516/crawler#2]
The QueueManager needs to know if ResultWorker is processing because the QueueManager feeds the SslyzeWorker  with targets and collect the results. So if there is no ResultWorker who process the results the result queue will be getting bigger and bigger. That means the QueueManager have to stop to feed the SslyzeWorker if the result queue have reached a certain limit to avoid memory overflow.

**Comment by MyMindMyBodyMySoul** [comment]
Added a maximum size for result_queue of 500 results.
The threshold value is not final and can still be altered as needed.

Small description:
result_queue ist now capped at 500 entries
queue_manager.next_host() will return URLs as long the result_queue is not full (< 500 entries).
If result_queue is full, next_host will return "None, none"

Link to the corresponding commit:
https://github.com/hft-swp2-ws1516/crawler/commit/02e9be4b174af282c9ed28a9f69e934900830e5f
